apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-svc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.helm.sh/stable"
    targetRevision: 5.5.6
    chart: grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: {}
